global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: "conjur"
    static_configs:
      - targets:
        - "conjur:3000"
        - "pg-prometheus-exporter:9187"
