version: "3"
services:
  dev:
    image: registry2.itci.conjur.net/cyberark/ubuntu-ruby-fips:20.04-9c1da20
    working_dir: /src
    volumes:
      - .:/src

  test:
    image: policy-parser-test
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ci/test.sh
    environment:
      - DEBUG
    volumes:
      - .:/src
