name: Enforce Git Rules

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, edited ]

jobs:
  rebase_job:
    runs-on: ubuntu-latest
    name: Enforce rebasing

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Is Rebased on master?
      uses: cyberark/enforce-rebase@v2

  commit_style:
    runs-on: ubuntu-latest
    name: Enforce commit style

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check commit style
      uses: cyberark/enforce-commit-style@v1
      with:
        subject-length: 72

  connection_to_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR is connected to a JIRA issue
        uses: JJ/github-pr-contains-action@releases/v0
        with:
          github-token: ${{github.token}}
          bodyContains: 'ONYX|CONJSE'